####
# Travis configuration for codeception-drupal-module.
####

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendir/bin/phpcs src --standard=PSR2
  - vendor/bin/phpspec run --format=pretty
